### ISSUE TITLE
Build Tool includes unused scenes marked as an AssetBundle

### ISSUE THREAD

**Issue by tinnystudios** [LiminalVR/LiminalSdk-UnityPackage#10]
Currently we are only supporting 1 scene that is marked as an AssetBundle. If there is another scene marked as an asset bundle, it will also be included by not used and may or may not dramatically increase the project size.

**Comment by MichaelLiminal** [comment]
Fixed by having the user select which scene to build in the menu (or if left blank, using the currently open scene).
