### ISSUE TITLE
Build Window: Need Set As Main Application

### ISSUE THREAD

**Issue by tinnystudios** [LiminalVR/LiminalSdk-UnityPackage#2]
The build window need to allow us to have multiple scene setup. Say we want to create a test scene to build as a limapp, we need to go Liminal -> Setup App Scene which is fine, however that method is also trying to modify the scene. 

We don't want that.

So another method such as Liminal -> Set As Main would allow flexibility in working with Liminal SDK

**Comment by MichaelLiminal** [comment]
Removed code that assigns the current scene to the appscene asset bundle. Instead, it only does that to the scene set as the target scene in the build window.
